start-at-login = true
after-startup-command = []
automatically-unhide-macos-hidden-apps = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true


default-root-container-layout = 'tiles'

default-root-container-orientation = 'horizontal'


[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10
