# -- -- -- -- -- -- -- -- -- -- #
# --     GLOBAL ZPROFILE     -- #
# -- -- -- -- -- -- -- -- -- -- #
# --      /etc/zprofile      -- #
# -- -- -- -- -- -- -- -- -- -- #

if (( TOGGLE_PATH_HELPER )); then
  if [[ -x /usr/libexec/path_helper ]]; then
    eval "$(/usr/libexec/path_helper -s)"
  fi
fi
