c_black #11111b
c_white #cdd6f4
c_rosewater #f5e0dc 
c_flamingo #f2cdcd
c_pink #f5c2e7
c_mauve #cba6f7
c_red #f38ba8
c_maroon #eba0ac
c_peach #fab387
c_yellow #f9e2af
c_green #a6e3a1
c_teal #94e2d5
c_sky #89dceb
c_sapphire #74c7ec
c_blue #89b4fa
c_lavender #b4befe
c_mantle #181825
c_base #1e1e2e
c_surface #45475a
c_overlay #7f849c
c_subtext #bac2de
