# -- KEYMAPS -- #

# Open a new OS Window (CMD+Shift + N)
map cmd+shift+n new_os_window

# Open new tab (CMD + N)
map cmd+n launch --type=tab --cwd=current

# Switch Tabs (CMD+Alt + <-/->)
map cmd+alt+left  previous_tab
map cmd+alt+right next_tab

# Reorder Tabs (CMD+Alt+Shift + <-/->)
map cmd+alt+shift+left  move_tab_backward
map cmd+alt+shift+right move_tab_forward

# -- REMAPS -- #
# Remap alt_keys to macos option-key functionality
map alt+5 send_text all [
map alt+6 send_text all ]
map alt+8 send_text all {
map alt+9 send_text all }
map alt+7 send_text all |
map alt+shift+7 send_text all \\
map cmd+ctrl+l send_text all @
map alt+n send_text all ~
