# -- Theme -- #
include themes/catppuccin-mocha.conf

# -- Font -- #
font_family family="Caskaydia Nerd Font Mono"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14.0

# -- Tab-Bar -- #
tab_bar_min_tabs 1
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# -- Mouse -- #
mouse_hide_wait 3.0

# -- Window -- #
remember_window_size no
initial_window_width 1280
initial_window_height 720
hide_window_decorations titlebar-only
window_padding_width 12 12 12 12

# -- Cursor -- #
shell_integration no-cursor
cursor #cba6f7
cursor_shape block
cursor_shape_unfocused hollow

# -- Scrollbar -- #
scrollback_lines 10000
scrollbar scrolled-or-hovered
scrollbar_interactive yes
scrollbar_width 2.0
scrollbar_hover_width 2.0
scrollbar_hitbox_expansion 10.0
scrollbar_radius 0.5
scrollbar_gap 0.0
scrollbar_min_handle_height 5.0

scrollbar_handle_opacity 0.1
scrollbar_track_opacity 0.0
scrollbar_track_hover_opacity 0.0
scrollbar_handle_color #cba6f7

