" Clipboard
set clipboard^=unnamed,unnamedplus " Enable Shared Clipboard (MacOS & Linux)

" Line Numbers
set number          " Show line numbers
set relativenumber  " Show relative line numbers

" Indentation
set expandtab       " Use spaces instead of tabs
set tabstop=2       " Number of spaces a <Tab> counts for
set shiftwidth=2    " Number of spaces to use for autoindent

" Code Options
filetype on
syntax on           " Enable syntax highlighting
