# -- UI -- #
gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  border: rounded
  sidePanelWidth: 0.25
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: false
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    searchingActiveBorderColor:
      - "#f9e2af"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    inactiveViewSelectedLineBgColor:
      - "#6c7086"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    cherryPickedCommitBgColor:
      - "#45475a"
    markedBaseCommitFgColor:
      - "#89b4fa"
    markedBaseCommitBgColor:
      - "#f9e2af"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
  authorColors:
    "*": "#b4befe"
# -- GIT -- #
git:
  diffRenderers:
    - name: delta
      type: stdinFilter
      colorArg: always
      command: >-
        delta --paging=never
        --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
# -- OS -- #
os:
  editPreset: nvim
