# -- -- -- -- -- -- -- -- -- -- -- #
# --        GLOBAL BASHRC       -- #
# -- -- -- -- -- -- -- -- -- -- -- #
# --         /etc/bashrc        -- #
# -- -- -- -- -- -- -- -- -- -- -- #

# System-wide bashrc file for interactive bash(1) shells.

# Default Prompt Bar
if [ -z "$PS1" ]; then
   return
fi
PS1='\h:\W \u\$ '

# Make bash check its window size after a process completes
shopt -s checkwinsize

# Source Global Configs for Terminals (e.g: /etc/bashrc_Apple_Terminal)
[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"

# Source User bashrc Config
if [[ -f "${HOME}/.bashrc" ]]; then
  source "${HOME}/.bashrc"
fi
