# -- -- -- -- -- -- -- -- -- -- #
# --     GLOBAL ZPROFILE     -- #
# -- -- -- -- -- -- -- -- -- -- #
# --      /etc/zprofile      -- #
# -- -- -- -- -- -- -- -- -- -- #

# Setup user specific overrides for this in ~/.zprofile. See zshbuiltins(1)
# and zshoptions(1) for more details.

if [ -z "$LANG" ]; then
	export LANG=C.UTF-8
fi
